### ISSUE TITLE
readbin3d_all should return primitives, not conserved variables

### ISSUE THREAD

**Issue by meithan** [esquivas/Guacho-v1.2#4]
This is usually what the user wants for plotting / post-processing.

**Comment by esquivas** [comment]
Now the function that reads the blocks computes the primitives and scale them to cgs.
To obtain the gas pressure or the B field components in case MHD is enabled, the kwarg mhd has to be set to True.
e.g. 
`Pgas = readbin3d_all(nout=nout,neq=4,path=path,verbose=False, mhd = True)`
Please test, and let me know if it's working properly to close the issue.

**Comment by esquivas** [comment]
Tests were OK.
